package com.rundas.cgc;

import com.gregtechceu.gtceu.api.addon.GTAddon;
import com.gregtechceu.gtceu.api.addon.IGTAddon;
import com.gregtechceu.gtceu.api.registry.registrate.GTRegistrate;

import com.rundas.cgc.common.material.CGCElements;
import net.minecraft.data.recipes.FinishedRecipe;

import com.rundas.cgc.common.material.CGCTagPrefixes;
import com.rundas.cgc.common.recipe.AutogeneratedRecipes;

import java.util.function.Consumer;

@SuppressWarnings("unused")
@GTAddon
public class CreatingGregCoreGTAddon implements IGTAddon {

    @Override
    public GTRegistrate getRegistrate() {
        return CreatingGregCore.CGC_REGISTRATE;
    }

    @Override
    public void initializeAddon() {}

    @Override
    public String addonModId() {
        return CreatingGregCore.MOD_ID;
    }

    @Override
    public void registerTagPrefixes() {
        CGCTagPrefixes.init();
    }

    @Override
    public void addRecipes(Consumer<FinishedRecipe> provider) {
        AutogeneratedRecipes.init(provider);
    }

    @Override
    public void registerElements() {
        CGCElements.init();
    }
}
