package com.rundas.cgc.common.material;

import com.gregtechceu.gtceu.api.data.chemical.material.properties.IMaterialProperty;
import com.gregtechceu.gtceu.api.data.chemical.material.properties.MaterialProperties;

/**
 * @param tier Voltage Tier, which all autogenerated recipes using this Material use.
 */
public record PhysicsProperty(int tier, double formationEnthalpy) implements IMaterialProperty {

    @Override
    public void verifyProperty(MaterialProperties properties) {}
}
