package com.rundas.cgc.common.recipe;

import com.gregtechceu.gtceu.api.GTValues;
import com.gregtechceu.gtceu.api.data.chemical.material.Material;
import com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey;
import com.gregtechceu.gtceu.common.unification.material.MaterialRegistryManager;
import com.rundas.cgc.common.material.CGCMaterialFlags;
import com.rundas.cgc.common.material.CGCPropertyKeys;
import com.rundas.cgc.common.material.NuclearProperty;
import com.rundas.cgc.common.material.SolutionProperty;
import net.minecraft.data.recipes.FinishedRecipe;

import java.util.List;
import java.util.function.Consumer;

import static com.gregtechceu.gtceu.api.data.tag.TagPrefix.dust;
import static com.gregtechceu.gtceu.common.data.GTRecipeTypes.CENTRIFUGE_RECIPES;
import static com.gregtechceu.gtceu.common.data.GTRecipeTypes.MIXER_RECIPES;
import static com.rundas.cgc.common.material.CGCMaterials.FreeNeutronGas;
import static com.rundas.cgc.common.recipe.CGCRecipeTypes.*;
import static com.rundas.cgc.util.CGCMaterialUtil.getMolarAmount;

public class AutogeneratedRecipes {
    public static void init(Consumer<FinishedRecipe> provider) {
        for (Material material : MaterialRegistryManager.getInstance().getRegisteredMaterials()) {
            int tier = material.getProperty(CGCPropertyKeys.PHYSICS).tier();
            if (material.hasProperty(CGCPropertyKeys.SOLUTION)) {
                processSolutions(provider, material, tier);
            }
            if (material.hasFlag(CGCMaterialFlags.IS_ROASTED)) {
                processRoastedDustDecomposition(provider, material, tier);
            }
            if (material.hasProperty(CGCPropertyKeys.NUCLEAR)) {
                processNuclearRecipes(provider, material, tier);
            }
        }
    }

    private static void processNuclearRecipes(Consumer<FinishedRecipe> provider, Material material, int tier) {
        NuclearProperty property = material.getProperty(CGCPropertyKeys.NUCLEAR);
        processIsotopicStabilizerRecipe(provider, material, property, tier);
        processDecayHastenerRecipes(provider, material, property);
        processDecayGeneratorRecipes(provider, material, property, tier);
        //processFissionReactorRecipes(provider, material, property, tier);
    }

    private static void processIsotopicStabilizerRecipe(Consumer<FinishedRecipe> provider, Material material, NuclearProperty property, int tier) {
        Material stable = property.stableMaterial();
        int neutrons = Math.toIntExact(material.getNeutrons() - stable.getNeutrons());
        if (material.hasProperty(PropertyKey.DUST)) {
            if (stable.hasProperty(PropertyKey.DUST)) {
                if (neutrons > 0) {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputItems(dust, material)
                            .outputItems(dust, stable)
                            .outputFluids(FreeNeutronGas.getFluid(neutrons))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                } else {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputItems(dust, material)
                            .inputFluids(FreeNeutronGas.getFluid(neutrons))
                            .outputItems(dust, stable)
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                }
            } else {
                if (neutrons > 0) {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputItems(dust, material)
                            .outputFluids(stable.getFluid(1000), FreeNeutronGas.getFluid(neutrons))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                } else {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputItems(dust, material)
                            .inputFluids(FreeNeutronGas.getFluid(neutrons))
                            .outputFluids(stable.getFluid(1000))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                }
            }
        } else {
            if (stable.hasProperty(PropertyKey.DUST)) {
                if (neutrons > 0) {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputFluids(material.getFluid(1000))
                            .outputItems(dust, stable)
                            .outputFluids(FreeNeutronGas.getFluid(neutrons))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                } else {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputFluids(material.getFluid(1000), FreeNeutronGas.getFluid(neutrons))
                            .outputItems(dust, stable)
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                }
            } else {
                if (neutrons > 0) {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputFluids(material.getFluid(1000))
                            .outputFluids(stable.getFluid(1000), FreeNeutronGas.getFluid(neutrons))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                } else {
                    ISOTOPIC_STABILIZER_RECIPES.recipeBuilder("stabilizing_" + material.getUnlocalizedName())
                            .inputFluids(material.getFluid(1000), FreeNeutronGas.getFluid(neutrons))
                            .outputFluids(stable.getFluid(1000))
                            .EUt(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
                }
            }
        }

    }

    private static void processDecayHastenerRecipes(Consumer<FinishedRecipe> provider, Material material, NuclearProperty property) {
        if (material.hasProperty(PropertyKey.DUST)) {
            if (property.alphaDecay() != null) {
                if (property.alphaDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(1).inputItems(dust, material)
                            .outputItems(dust, property.alphaDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(1).inputItems(dust, material)
                            .outputFluids(property.alphaDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
            if (property.betaPlusDecay() != null) {
                if (property.betaPlusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(2).inputItems(dust, material)
                            .outputItems(dust, property.betaPlusDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(2).inputItems(dust, material)
                            .outputFluids(property.betaPlusDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
            if (property.betaMinusDecay() != null) {
                if (property.betaMinusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(3).inputItems(dust, material)
                            .outputItems(dust, property.betaMinusDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(3).inputItems(dust, material)
                            .outputFluids(property.betaMinusDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
        } else {
            if (property.alphaDecay() != null) {
                if (property.alphaDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(1)
                            .inputFluids(material.getFluid(1000))
                            .outputItems(dust, property.alphaDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(1)
                            .inputFluids(material.getFluid(1000))
                            .outputFluids(property.alphaDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
            if (property.betaPlusDecay() != null) {
                if (property.betaPlusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(2)
                            .inputFluids(material.getFluid(1000))
                            .outputItems(dust, property.betaPlusDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(2)
                            .inputFluids(material.getFluid(1000))
                            .outputFluids(property.betaPlusDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
            if (property.betaMinusDecay() != null) {
                if (property.betaMinusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(3)
                            .inputFluids(material.getFluid(1000))
                            .outputItems(dust, property.betaMinusDecay().getA())
                            .duration((int) material.getMass()).save(provider);
                } else {
                    DECAY_HASTENER_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName())
                            .circuitMeta(3)
                            .inputFluids(material.getFluid(1000))
                            .outputFluids(property.betaMinusDecay().getA().getFluid(1000))
                            .duration((int) material.getMass()).save(provider);
                }
            }
        }
    }

    private static void processDecayGeneratorRecipes(Consumer<FinishedRecipe> provider, Material material, NuclearProperty property, int tier) {
        if (material.hasProperty(PropertyKey.DUST)) {
            if (property.alphaDecay() != null) {
                if (property.alphaDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(1)
                            .outputItems(dust, property.alphaDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.alphaDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(1)
                            .outputFluids(property.alphaDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.alphaDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
            if (property.betaPlusDecay() != null) {
                if (property.betaPlusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(2)
                            .outputItems(dust, property.betaPlusDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaPlusDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(2)
                            .outputFluids(property.betaPlusDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaPlusDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
            if (property.betaMinusDecay() != null) {
                if (property.betaMinusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(3)
                            .outputItems(dust, property.betaMinusDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaMinusDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputItems(dust, material)
                            .circuitMeta(3)
                            .outputFluids(property.betaMinusDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaMinusDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
        } else {
            if (property.alphaDecay() != null) {
                if (property.alphaDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(1)
                            .outputItems(dust, property.alphaDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.alphaDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("alpha_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(1)
                            .outputFluids(property.alphaDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.alphaDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
            if (property.betaPlusDecay() != null) {
                if (property.betaPlusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(2)
                            .outputItems(dust, property.betaPlusDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaPlusDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_plus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(2)
                            .outputFluids(property.betaPlusDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaPlusDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
            if (property.betaMinusDecay() != null) {
                if (property.betaMinusDecay().getA().hasProperty(PropertyKey.DUST)) {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(3)
                            .outputItems(dust, property.betaMinusDecay().getA())
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaMinusDecay().getB() / GTValues.VA[tier])).save(provider);
                } else {
                    DECAY_GENERATOR_RECIPES.recipeBuilder("beta_minus_decaying_" + material.getUnlocalizedName() + "_in_generator")
                            .inputFluids(material.getFluid(1000))
                            .circuitMeta(3)
                            .outputFluids(property.betaMinusDecay().getA().getFluid(1000))
                            .outputEU(GTValues.VA[tier]).duration((int) (property.betaMinusDecay().getB() / GTValues.VA[tier])).save(provider);
                }
            }
        }
    }

    private static void processRoastedDustDecomposition(Consumer<FinishedRecipe> provider, Material material, int tier) {
        CENTRIFUGE_RECIPES.recipeBuilder("decomposing_" + material.getUnlocalizedName())
                .inputItems(dust, material, getMolarAmount(material))
                .outputItems(material.getMaterialComponents())
                .inputEU(GTValues.VA[tier]).duration((int) material.getMass()).save(provider);
    }

    private static void processSolutions(Consumer<FinishedRecipe> provider, Material material, int tier) {
        SolutionProperty property = material.getProperty(CGCPropertyKeys.SOLUTION);
        processSolutionMixing(provider, material, property, tier);
        processSolutionCrystallization(provider, property.solutions().get(0), property.solutions().get(1), tier);
        processSolutionDehydration(provider, material, property.solutions().get(0), tier);
    }

    private static void processSolutionMixing(Consumer<FinishedRecipe> provider, Material material, SolutionProperty property, int tier) {
        final Material solvent = property.solvent();
        String name;
        for (int i = 1; i < property.solutions().size(); i++) {
            if (i == 1) {
                name = "mixing_" + material.getUnlocalizedName() + solvent.getUnlocalizedName() + "_solution";
                processRegularSolutionMixing(provider, material, solvent, property.solutions().get(1), tier, name);
            } else if (i == 2) {
                name = "mixing_diluted_" + material.getUnlocalizedName() + solvent.getUnlocalizedName() + "_solution";
                process1XDilutedSolutionMixing(provider, material, solvent, property.solutions().get(1), property.solutions().get(2), tier, name);
            } else {
                name = "mixing_" + (i - 1) + "x_diluted_" + material.getUnlocalizedName() + solvent.getUnlocalizedName() + "_solution";
                processFurtherDilutedSolutionMixing(provider, material, solvent, property.solutions().get(i), property.solutions(), i, tier, name);
            }
        }
    }

    private static void processRegularSolutionMixing(Consumer<FinishedRecipe> provider, Material material, Material solvent, Material solution, int tier, String name) {
        MIXER_RECIPES.recipeBuilder(name)
                .inputItems(dust, material, getMolarAmount(material))
                .circuitMeta(1)
                .inputFluids(solvent.getFluid(1000))
                .outputFluids(solution.getFluid(1000))
                .inputEU(GTValues.VA[tier]).duration(20).save(provider);
    }

    private static void process1XDilutedSolutionMixing(Consumer<FinishedRecipe> provider, Material material, Material solvent, Material concentratedSolution, Material dilutedSolution, int tier, String name) {
        MIXER_RECIPES.recipeBuilder(name)
                .inputItems(dust, material)
                .circuitMeta(2)
                .inputFluids(solvent.getFluid(2000))
                .outputFluids(dilutedSolution.getFluid(2000))
                .inputEU(GTValues.VA[tier]).duration(40).save(provider);

        MIXER_RECIPES.recipeBuilder(name)
                .circuitMeta(2)
                .inputFluids(concentratedSolution.getFluid(1000), solvent.getFluid(1000))
                .outputFluids(dilutedSolution.getFluid(2000))
                .inputEU(GTValues.VA[tier]).duration(40).save(provider);
    }

    private static void processFurtherDilutedSolutionMixing(Consumer<FinishedRecipe> provider, Material material, Material solvent, Material solution, List<Material> solutions, int tier, int i, String name) {
        MIXER_RECIPES.recipeBuilder(name)
                .inputItems(dust, material)
                .circuitMeta(i)
                .inputFluids(solvent.getFluid(i * 1000))
                .outputFluids(solution.getFluid(i * 1000))
                .inputEU(GTValues.VA[tier]).duration(i * 20).save(provider);

        for (int j = 1; j <= i - 1; j++) {
            MIXER_RECIPES.recipeBuilder(name)
                    .circuitMeta(j)
                    .inputFluids(solutions.get(i - j).getFluid(1000), solvent.getFluid(j * 1000))
                    .outputFluids(solution.getFluid(i * 1000))
                    .inputEU(GTValues.VA[tier]).duration(j * 20).save(provider);
        }
    }

    private static void processSolutionCrystallization(Consumer<FinishedRecipe> provider, Material solution, Material crystallizedSolution, int tier) {
        CRYSTALLIZER_RECIPES.recipeBuilder("crystallizing_" + solution.getUnlocalizedName())
                .inputFluids(solution.getFluid(1000))
                .outputFluids(crystallizedSolution.getFluid(1000))
                .inputEU(GTValues.VA[tier]).duration((int) solution.getMass()).save(provider);
    }

    private static void processSolutionDehydration(Consumer<FinishedRecipe> provider, Material material, Material solution, int tier) {
        DEHYDRATOR_RECIPES.recipeBuilder("dehydrating_" + solution.getUnlocalizedName())
                .inputFluids(solution.getFluid(1000))
                .outputItems(dust, material, getMolarAmount(material))
                .inputEU(GTValues.VA[tier]).duration((int) solution.getMass()).save(provider);
    }
}
